### ISSUE TITLE
Validate that labels do not contain underscores

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io-modules/resin-compose-parse#18]
Currently if one tries to make a build with labels like:
```
labels:
  io.resin.features.dbus: "true"
  io.resin.features.kernel_modules: "true"
  io.resin.features.firmware: "true"
  io.resin.features.supervisor_api: "true"
```

The supervisor fails and complains about "invalid apps". In the case a user uses these invalid labesl we should make the build error out and instruct them to use the correct labels
